adress: 0.0.0.0:9000
deployfile: .deploy.yml
sessionsecretkey: kurf56ys
logs:
   error: error.log
   gohub: info.log
oauth:
  clientid: 95516ec894645a4366f2
  clientsecret: fee08040cfd8aafba8c3ff6ca2b85a084cc836de
  scopes:
    - user
    - user:email
    - repo
    - repo:status
    - read:repo_hook
    - write:repo_hook
    - admin:repo_hook
oauthstatestring: ikop2n3ddd4