host: komrakov@komrakov-stage.smart-crowd.ru
pull_request:
  commands:
    - status: pending
    - ssh: whereis git
    - ssh: cd /
    - ssh: ls
    - ssh: wheris {{sha}}
    - status: success
push:
  branch: refs/heads/master
  commands:
    - exec: go get -u github.com/alexkomrakov/gohub & || :
    - status: success
