host: komrakov@komrakov-stage.smart-crowd.ru
pull_request:
  commands:
    - status: pending
    - ssh: whereis git
    - ssh: cd /
    - ssh: ls
    - ssh: wheris {{sha}}
    - status: success
push:
  branch: refs/heads/master
  commands:
    - exec: pkill -f main
    - exec: go run ~/go/src/github.com/alexkomrakov/gohub/main.go
    - status: success