pull_request:
  host: root@188.166.34.149:22
  commands:
    - status: pending
    - ssh: whereis git
    - ssh: cd /
    - ssh: ls
    - ssh: wheris {{sha}}
    - status: success
  onError:
    - status: error
push:
   branch: refs/heads/master
   host: root@188.166.34.149:22
   commands:
     - ssh: go get -u github.com/alexkomrakov/gohub
test:
  host: root@188.166.34.149:22
  commands:
    - ssh: ifconfig